config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :courses do
    get 'update_chapter_numbers'
  end

  resources :questions

   root 'courses#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  layout 'flatly'
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    chapterno = params[:chapter]|| "all"
    chapterno = chapterno.to_i
    @chapter_questions = (chapterno == 0 ? @course.questions : @course.questions.where("chapter >= #{chapterno} and chapter < #{chapterno+1}").order(index_number: :desc))
    @chapternumbers = @course.questions.collect(&:chapter).uniq
    answerd = params[:answerd]|| "all"
    if answerd == "false"
      @chapter_questions = @chapter_questions.where("answer is null or answer=''")
    elsif answerd == "true"
      @chapter_questions = @chapter_questions.where("answer is not null or answer<>''")
    end

    @chapter_questions.order(index_number: :desc)


  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_chapter_numbers
    @course = Course.find(params[:course_id])
    chapterno = params[:chapter]|| "all"
    chapterno = chapterno.to_i
    @chapternumbers = @course.questions.collect(&:chapter).uniq

    @chapter_questions = (chapterno == 0 ? @course.questions : @course.questions.where("chapter >= #{chapterno} and chapter < #{chapterno.to_i+1}").order(index_number: :asc))
    questionsCounter = 1
    @chapter_questions.each do |question|
      question.update_attribute(:index_number, questionsCounter)
      puts question.index_number, questionsCounter
      questionsCounter+=1
    end
    render :show
  end
  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout 'flatly'
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order(created_at: :desc)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.course_id = params[:course_id] if params[:course_id]
    @prev_question = @question.course.questions.last
    if @prev_question.present?
      @question.index_number = @prev_question.index_number + 0.01
      @question.chapter = @prev_question.chapter
    else
      @question.index_number = 0
      @question.chapter = 1
    end
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to course_path(@question.course, chapter: @question.chapter), notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to course_path(@question.course, chapter: @question.chapter), notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    tmpcourse = @question.course
    tmpChapter = @question.chapter
    @question.destroy
    respond_to do |format|
      format.html { redirect_to course_path(tmpcourse, chapter: tmpChapter), notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :answer, :course_id, :chapter, :index_number)
    end

    def latest_index_number
      Question.last.index_number
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/courses/_form.html.haml
= form_for @course, html: { class: "form form-horizontal course" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), courses_path, :class => 'btn btn-default'

app/views/courses/edit.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/index.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr{class:"info"}
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @courses.each do |course|
      %tr         
        %td=link_to  course.name, course_path(course)
        %td=l course.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(course), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(course), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_course_path, :class => 'btn btn-primary'

app/views/courses/new.html.haml
- model_class = Course
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/courses/show.html.haml
- model_class = Course
.page-header
  %h1=@course.name




= link_to 'New Question', new_question_path(course_id:@course.id), :class => 'btn btn-success'
= link_to 'show all',course_path(@course.id, chapter:"all"), :class => 'btn btn-success'
= link_to 'answerd',course_path(@course.id, answerd:"true"), :class => 'btn btn-success'
= link_to 'unanswerd',course_path(@course.id, answerd:"false"), :class => 'btn btn-success'
-@chapternumbers.each do |chno|
  = link_to chno,course_path(@course.id, chapter:chno), :class => 'btn btn-success'
%table{class:"table table-striped table-hover"}
  %tr{class:"info"}
    %th index
    %th Question
    %th Answer
    %th

    -@chapter_questions.each do |question|# @course.questions.all.order(chapter: :asc,index_number: :asc).each do |question|
      %tr
        %td= "#{question.chapter}-#{question.index_number.to_s}"

        %td= link_to question.question, edit_question_path(question)
        %td= raw question.answer
        %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

= link_to t('.back', :default => t("helpers.links.back")), courses_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_course_path(@course), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), course_path(@course), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
=content_for :page_actions do
  %li= link_to 'New Question', new_question_path(course_id:@course.id), :class => 'btn btn-success'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uni</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/flatly.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "uni"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "flatly", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body
    =render "shared/navbar"
    .well
      = yield

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    =javascript_include_tag 'application'
    = javascript_include_tag "flatly"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/questions/_form.html.haml
.well{:"data-no-turbolink" => true}
  = form_for @question, class:"form-horizontal" do |f|
    - if @question.errors.any?
      #error_explanation
        %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
        %ul
          - @question.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :question, class:"control-label"
      = f.text_area :question, class:"long_text_field", class:"form-control"
    .actions
      = f.submit 'Save'  ,  class:"btn btn-primary"
    .form-group
      = f.label :answer, class:"control-label"
      = f.text_area :answer, class:"long_text_field", :class => 'ckeditor'
    .form-group
      = f.label :course_id, class:"control-label"
      = f.collection_select(:course_id, Course.all, :id, :name, {},{class:"form-control"})
    .form-group  
      = f.label :chapter, class:"control-label"
      = f.text_field :chapter, value:(@question.chapter || 999) , class:"form-control"
    .form-group  
      = f.label :index_number, class:"control-label"
      = f.text_field :index_number, class:"form-control"
      = f.submit 'Save',  class:"btn btn-primary"
=content_for :page_actions do
  %li= link_to "save", "#", :id => "nav_save_question"

=content_for :page_javascript do
  :javascript
    $( document ).ready(function(){
      $("#question_question").focus();
      $("#nav_save_question").click(function(){
        $("#new_question").submit();
      })
    });

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

=content_for :page_actions do
  %li= link_to 'Back to course', @question.course, class:"btn btn-info"
.well.previous-question
  %h5 previous question
  -q = Question.last
  =link_to q.index_number.to_s + "- " + q.question, edit_question_path(q) if q.present?

app/views/questions/index.html.haml
%h1 Listing questions
= link_to 'New Question', new_question_path, class:"btn"
%table
  %tr
    %th Course
    %th Number
    %th Question
    %th Answer
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.course_id.to_s + '.' + question.chapter.to_s
      %td= question.index_number
      %td= link_to question.question, edit_question_path(question)
      %td= raw question.answer
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/questions/new.html.haml
-q = Question.last
%br
%h3
  ="New question for"
  ="#{ @question.course.name}"

= render 'form'
.well.previous-question
  %h5 previous question

  =link_to q.index_number.to_s + "- " + q.question, edit_question_path(q) if q.present?
=content_for :page_actions do
  %li= link_to 'Back to course', @question.course, class:"btn btn-info"

app/views/questions/show.html.haml
%p#notice= notice

%p
  %h3 
    = @question.question
    ?
%p
  =raw @question.answer
%p
  %b Course:
  = @question.course_id

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/shared/_navbar.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header

      =link_to "HOME", root_path, class:"navbar-brand"
      %button.navbar-toggle{"data-target" => "#navbar-main", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    #navbar-main.navbar-collapse.collapse
      %ul.nav.navbar-nav

      %ul.nav.navbar-nav.navbar-right
        =yield (:page_actions) if content_for?(:page_actions)